config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
  root 'top#hello'
  get "hello/user"=>"top#user",as:"user_index"
  resources :tweets 
  

  post "comment/create/:tweet_id"=>"comments#create",as:'tweet_comments'
  delete "comment/destroy/:id"=>"comments#destroy",as:"comment_destroy"

  resources :users, :only => [:show]

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  post "likes/:tweet_id"=>"likes#create",as:"like"
  delete "likes/:tweet_id"=>"likes#destroy",as:"like_delete"
  post "relationship/:id"=>"relationships#create",as:"relationship_create"
  delete "relationship/:id"=>"relationships#destroy",as:"relationship_destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entrie.rb
class Entrie < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :body, presence: true,    length: { maximum: 140 }    
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :post

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @tweet=Tweet.find_by(id:params[:tweet_id])
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    
  end

  def destroy
    @tweet=Tweet.find_by(id:params[:tweet_id])
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entrie.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entrie.create(params.require(:entrie).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entrie.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.order(id: "DESC")
      @message = Message.new
      @entries = Entrie.where(room_id:@room.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def hello
  end
  def user
    @users=User.all.order(id: "DESC")
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets=Tweet.all.order(id: "DESC")
  end
  
  def new 
    @tweet=Tweet.new
  end 

  def show
    @tweet=Tweet.find(params[:id])
    @like = Like.new
    @comment=Comment.new
    @comments=Comment.where(tweet_id:@tweet.id).order(id: "DESC")
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      flash[:notice]="Your post was updated!"
      redirect_to :action => "show", :id => @tweet.id
    else
      render("tweets/new")
    end
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      flash[:notice]="Your post was sheared!"
      redirect_to :action => "index"
    else
      render("tweets/new")
    end
  end 

  def destroy
    Tweet.find(params[:id]).destroy
    flash[:notice]="Your post was deleted!"
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @tweets=Tweet.where(user_id:@user.id).order(id: "DESC") 
    @followings=@user.followings
    @followers=@user.followers

    @currentUserEntry=Entrie.where(user_id: current_user.id)
    @userEntry=Entrie.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entrie.new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<% if current_user.already_liked?(tweet) %>
  <%=link_to like_delete_path(tweet.id), method: :delete, remote: true do%>
     <i class="fas fa-heart like1"></i>
  <%end%>  
  <div class="like-number"><%= tweet.likes.count %></div>
  

<% else %>
  <%=link_to like_path(tweet.id) , method: :post, remote: true do%>
    <i class="far fa-heart like2"></i>
  <%end%>  
  <div class="like-number"><%= tweet.likes.count %></div>
  
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @tweet.id %>').html("<%= j(render partial: 'likes/like', locals: {tweet: @tweet}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @tweet.id %>').html("<%= j(render partial: 'likes/like', locals: {tweet: @tweet}) %>");

app/views/rooms/show.html.erb
<div class="main">
  <div class="main-back">
    <div class="new">
      <h1 class="dm-header">
      DM room
       <% @entries.each do |e| %>
        <div class="user-name">
        <strong>
              <p><%= e.user.username %></p>
        </strong>
        </div>
      <% end %>
      </h1>
     
      <hr>
      <div class="chats">
      <div class="dm-posts">
          <%= form_for @message do |f| %>
            <%= f.text_field :body, placeholder: "Type your message! " , size: 70, class:"form-text-field" %>
              <%= f.hidden_field :room_id, value: @room.id %>
                <%= f.submit "post!",class: 'form-submit'%>
          <% end %>
        <div class="chat">
          <% if @messages.present? %>
            <% @messages.each do |m| %>
              <div class="chat-box">
                <%if m.user.admin?%>
                  <%=link_to user_path(m.user.id),class:"index-name" do%>
                    <p><i class="fas fa-certificate"></i><%=m.user.username%></p>
                  <%end%>
                <%else%>  
                  <%=link_to user_path(m.user.id),class:"index-name" do%>
                    <p><%=m.user.username%></p>
                  <%end%>
                <%end%>
                <div class="chat-hukidashi"> <strong><%= m.body %></strong> <br>
                  <%= m.created_at.strftime("%Y-%m-%d %H:%M")%>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
        
        </div>
      </div>
    </div>
  </div>
</div>