config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
  root 'top#hello'
  get "hello/user"=>"top#user",as:"user_index"
  resources :tweets 
  

  post "comment/create/:tweet_id"=>"comments#create",as:'tweet_comments'
  delete "comment/destroy/:id"=>"comments#destroy",as:"comment_destroy"

  resources :users, :only => [:show]

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  post "likes/:tweet_id"=>"likes#create",as:"like"
  delete "likes/:tweet_id"=>"likes#destroy",as:"like_delete"
  post "relationship/:id"=>"relationships#create",as:"relationship_create"
  delete "relationship/:id"=>"relationships#destroy",as:"relationship_destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :post

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @tweets=Tweet.where(user_id:@user.id).order(id: "DESC") 
    @followings=@user.followings
    @followers=@user.followers

    @currentUserEntry=Entrie.where(user_id: current_user.id)
    @userEntry=Entrie.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entrie.new
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="main">
  <div class="my-page">
    <div class="user-inf">
      <div class="user-inf-header">
        <% if @user.admin?  %>
        <p><i class="fas fa-certificate"></i><%= @user.username %></p>
        <%else%>
        <p><%= @user.username %></p>
        <%end%>
      </div>
      <div class="user-logo">
        <i class="fas fa-user-circle"></i>
      </div>
      <div class="follow-btn">
        <% unless current_user == @user %>
        <% if current_user.following?(@user) %>
        <%=link_to relationship_destroy_path(@user.id),method: :delete do%>
        <p class="unfollow">Unfolllow</p>
        <%end%>
        <% else %>
        <%=link_to relationship_create_path(@user.id), method: :post do%>
        <p class="follow">Folllow</p>
        <%end%>
        <% end %>

        <% if (current_user.following? @user) && (@user.following? current_user)  %>
        <% if @isRoom == true %>
        <a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">DM</a>
        <% else %>
        <%= form_for @room do |f| %>
        <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "DM", class:"  user-show-chat"%>
        <% end %>
        <% end %>
        <% end %>

        <% end %>
      </div>
      <div class="switch">
        <%if @user==current_user%>
        <p class="tab ">following</p>
        <p class="tab is-active"> My Tweet</p>
        <%end%>
      </div>
      <div class="follow-counter">
        <p>Following <%=@followings.count%></p>
        <p>Follower <%=@followers.count%></p>
        <p>Post <%=@tweets.count%></p>
      </div>
    </div>


    <div class="follow-tweet ">
      <div class="main-header my-page-header">
        <%= link_to tweets_path  do%>
        <p><i class="fas fa-undo-alt"></i>INDEX</p>
        <%end%>
        <%=link_to new_tweet_path do%>
        <p><i class="fas fa-plus"></i>New</p>
        <%end%>
      </div>
      <div class="my-page-tweet">
        <%Tweet.where(user_id:@followings.ids).order(id: "DESC").each do |t|%>
        <div class="tweet">

          <%=link_to user_path(t.user.id) ,class:"index-name" do%>
          <%if t.user.admin?%>
          <p><i class="fas fa-certificate"></i><%=t.user.username%></p>
          <%else%>
          <p><%=t.user.username%></p>
          <%end%>
          <%end%>

          <p class="index-body"><%=t.body%></p>
          <div class="tweet-menu">
            <%=link_to tweet_path(t.id),class:"non-danger" do%>
            <p>show</p>
            <%end%>
            <div class="like" id="likes_buttons_<%= t.id %>">
              <%= render partial: 'likes/like', locals: { tweet: t} %>
            </div>
          </div>
        </div>
        <%end%>
      </div>
    </div>
    <div class="follow-tweet is-show">
      <div class="main-header my-page-header">
        <%= link_to tweets_path  do%>
        <p><i class="fas fa-undo-alt"></i>INDEX</p>
        <%end%>
        <%=link_to new_tweet_path do%>
        <p><i class="fas fa-plus"></i>New</p>
        <%end%>
      </div>
      <div class="my-page-tweet">
        <%@tweets.each do |t|%>
        <div class="tweet">

          <%=link_to user_path(t.user.id),class:"index-name" do%>
          <p><%=t.user.username%></p>
          <%end%>

          <p class="index-body"><%=t.body%></p>
          <div class="tweet-menu">
            <div class="like" id="likes_buttons_<%= t.id %>">
              <%= render partial: 'likes/like', locals: { tweet: t} %>
            </div>
            <%=link_to tweet_path(t.id),class:"non-danger" do%>
            <p>show</p>
            <%end%>
            <%if current_user==t.user%>
            <%=link_to edit_tweet_path(t.id),class:"non-danger" do%>
            <p>edit</p>
            <%end%>
            <%=link_to tweet_path(t.id),method: :delete,class:"danger" do%>
            <p>delete</p>
            <%end%>
            <%end%>
          </div>
        </div>
        <%end%>
      </div>
    </div>
  </div>
</div>