config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
  root 'top#hello'
  get "hello/user"=>"top#user",as:"user_index"
  resources :tweets 
  

  post "comment/create/:tweet_id"=>"comments#create",as:'tweet_comments'
  delete "comment/destroy/:id"=>"comments#destroy",as:"comment_destroy"

  resources :users, :only => [:show]

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  
  post "likes/:tweet_id"=>"likes#create",as:"like"
  delete "likes/:tweet_id"=>"likes#destroy",as:"like_delete"
  post "relationship/:id"=>"relationships#create",as:"relationship_create"
  delete "relationship/:id"=>"relationships#destroy",as:"relationship_destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/entrie.rb
class Entrie < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :body, presence: true,    length: { maximum: 140 }    
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :tweets
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :post

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  def create
    @tweet=Tweet.find_by(id:params[:tweet_id])
    @like = current_user.likes.create(tweet_id: params[:tweet_id])
    
  end

  def destroy
    @tweet=Tweet.find_by(id:params[:tweet_id])
    @like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    @like.destroy
    
  end


end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entrie.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entrie.create(params.require(:entrie).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entrie.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages.order(id: "DESC")
      @message = Message.new
      @entries = Entrie.where(room_id:@room.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def hello
  end
  def user
    @users=User.all.order(id: "DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntranceApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.1/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag '/favicon.ico' %>
  <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico" />

  </head>

  <body>
  <header>
    <%if user_signed_in?%>
      <%=link_to user_path(current_user.id) do%>
        <p class="user-link"><%=current_user.username%></p>
      <%end%>
      <%=link_to root_path do%>
        <p>TOP</p>
      <%end%>
      <%=link_to tweets_path do%>
        <p>INDEX</p>
      <%end%>  
      <%=link_to new_tweet_path do%>
        <p>New</p>
      <%end%> 
      <%=link_to  destroy_user_session_path, method: :delete do%>
        <p>Log Out</p>
      <%end%> 
      <%if current_user.admin?%>
        <%=link_to user_index_path do %>
          <p>Users</p>
        <%end%>
      <%end%>
    <%else%>
      <%=link_to root_path do%>
        <p>TOP</p>
      <%end%>
      <%=link_to  new_user_session_path do%>
        <p>Log In</p>
      <%end%>
      <%=link_to   new_user_registration_path do%>
        <p>Sign up</p>
      <%end%>
    <%end%>
  </header>
   <%if flash[:notice]%>
        <div class="flash" id="flash">
        <%= flash[:notice]%>
        </div>
    <%end%>
    <%= yield %>
  </body>
</html>